// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // This config drives the Prisma CLI (migrations) only — the runtime
    // client connects via @prisma/adapter-pg using DATABASE_URL (pooled in
    // prod). Migrations need a DIRECT (non-pooled) connection on Neon, so
    // DIRECT_URL wins here when set.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
